sudo: false
language: node_js
cache:
  bundler: true
  directories:
  - node_modules
node_js:
- '0.10'
deploy:
  provider: npm
  skip_cleanup: true
  clean_up: false
  email: serveradmin@octoblu.com
  api_key:
    secure: Makb6nLpA1Qi3AK8ctCvRcxGexg9c+R9LgjDlVHiL8y+vmAViHCS0SRAUY7TcM4GLyRXgvl0alAuPuyQM4sslf5YsTA9ALR0yXl4TqaFBSZMIj0tLVxxqZwhfVCG0mZSKDmBZYE+0CE9FSjRTy+CsYJQm6fx4TRhRv9p4RTAGD+0vZwgcdQ2Z7wL6w+QP4HCZjj2drOXKkscAsCYtZq5sSC/VUPV1o7H06JTnLbfOs437Fd7vz0fczY3P02Z+TSGoxKYhairKzrNUXJVBevdnyDTPWulXG9KZt2P3bqw1LnwZ6YLYxnMy4NTW//ex1inXAMBhwSsV2nm1Rk0RtCt+r5LuT5p5lvEoo7MMkTBhsoC+wkeQ2U7yKQ+1Kcqhea65UPcos5UTa5Fz5BSUGFISxfl/HSmruaps4mfwNBOjz9o426J+tfrOQNsiXny3PhPbR9GQ41wuYKHPPiQtOCfiuFlRFwejh2yR//p4dmAdQh6yppJSyD7qFEls+HbK9WVIl55KPG6EPcstGiSLmZkgWeTcc3IO119OEEf8wxpMZZ8dlYiI/HjZLG+Nz9elx8+T6Ast5y9n0BcvQyST40IPuVV30FEcuSsOs7tLFYA1wCiBazA691udhab8TD1YVUVUGTEFElo4kIUsp055479Hget4/bYXektNcfNI5IJFDI=
  on:
    tags: true
    all_branches: true
